### PR TITLE
Debian package build instructions

### PR DESCRIPTION
**Pull request by smoe**
Hello,

I have the impression you committed d8869ec erroneously to the https://github.com/bmx-routing/bmx6/tree/debian branch you just created. Before pressing any accept button, you may want to perform a merge https://github.com/bmx-routing/bmx6/tree/debian with master to get that patch out of the way and then only have pristine Debian-only changes maintained in that branch.

So, following our mission outlined in https://github.com/bmx-routing/bmx6/issues/13 I have the package in a state that looks reasonably fine. Please help me in debian/control with
 * a better description of your package - the README.md would also benefit from a few lines for the less proficient. What helps me for descriptions I write is to address it to a 15 year old school kid that is a tech-affectionado but just does not have much of a vocabulary or context.
 * add your name to the Maintainer field and move mind to a new line starting with "Uploaders:". This prepares for your independence from me. For bmx7 we can have it the same way. 

I still need to have a look at your source code to learn how you import the modules. Until then I have spared the ldconfig in the (now non-existing) post-install script. I have also changed the directory to /usr/lib/bmx6 instead of having all libraries in /usr/lib directly. This likely needs a respective adjustment in the main source tree that I have not yet addressed, your feedback pending.

You will happily observe a man page. That was auto-created and then somewhat manually optimized for the impression I got with "nroff -man debian/bmx6.1". Please also have at look at that.
```
$ dpkg -c bmx6_0.0-1_amd64.deb
drwxr-xr-x root/root         0 2018-05-12 19:06 ./
drwxr-xr-x root/root         0 2018-05-12 19:06 ./usr/
drwxr-xr-x root/root         0 2018-05-12 19:06 ./usr/lib/
drwxr-xr-x root/root         0 2018-05-12 19:06 ./usr/lib/bmx6/
-rw-r--r-- root/root     10408 2018-05-12 19:06 ./usr/lib/bmx6/bmx6_http_info.so
-rw-r--r-- root/root     18752 2018-05-12 19:06 ./usr/lib/bmx6/bmx6_json.so
-rw-r--r-- root/root     34112 2018-05-12 19:06 ./usr/lib/bmx6/bmx6_quagga.so
-rw-r--r-- root/root     14456 2018-05-12 19:06 ./usr/lib/bmx6/bmx6_sms.so
-rw-r--r-- root/root     24608 2018-05-12 19:06 ./usr/lib/bmx6/bmx6_table.so
-rw-r--r-- root/root     14760 2018-05-12 19:06 ./usr/lib/bmx6/bmx6_topology.so
drwxr-xr-x root/root         0 2018-05-12 19:06 ./usr/sbin/
-rwxr-xr-x root/root    298992 2018-05-12 19:06 ./usr/sbin/bmx6
drwxr-xr-x root/root         0 2018-05-12 19:06 ./usr/share/
drwxr-xr-x root/root         0 2018-05-12 19:06 ./usr/share/doc/
drwxr-xr-x root/root         0 2018-05-12 19:06 ./usr/share/doc/bmx6/
-rw-r--r-- root/root       154 2018-05-12 19:06 ./usr/share/doc/bmx6/changelog.Debian.gz
-rw-r--r-- root/root      1202 2018-05-12 19:06 ./usr/share/doc/bmx6/copyright
drwxr-xr-x root/root         0 2018-05-12 19:06 ./usr/share/man/
drwxr-xr-x root/root         0 2018-05-12 19:06 ./usr/share/man/man1/
-rw-r--r-- root/root      1284 2018-05-12 19:06 ./usr/share/man/man1/bmx6.1.gz
```

Do you have suggestions for me how to perform a test?
How likely is it that users have bmx6 and bmx7 installed on the same machine? Should the package rather be called bmx with version 6 / 7?

Best,

Steffen

### CODE REVIEW

**Comment by aparcar** [comment]
> I have the impression you committed d8869ec erroneously [...]

I hope I just fixed that. Please remove the commit from your PR as it's merged to the _debian_ branch.

> Do you have suggestions for me how to perform a test?

I'll do some tests with a router and a VM once this is merged. I could send you the commands I use if you're interested to do the same.

>  How likely is it that users have bmx6 and bmx7 installed on the same machine? Should the package rather be called bmx with version 6 / 7?

Very, both versions aren't compatible with one another. While 7 is the planned successor, BMX6 is still heavily used as it has no crypto lib dependencies making it (easier) usable on small (legacy) 4MB flash routers.

I saw you're excluding the _uci_ plugin, I'd suggest to do the same with _iwinfo_.

**Comment by smoe** [comment]
I just removed some long text stating that I would not know how to remove your commit without a rebase or you merging with master what has been commited already. To keep it short, please kindly rename/delete the current debian branch and craft me a new one.

**Comment by aparcar** [comment]
> To keep it short, please kindly rename/delete the current debian branch and craft me a new one.

Done

**Comment by smoe** [comment]
Funnily enough the prior pull request was not removed. Looks good now. I suggest you accept the patch and then improve the description in the debian/control file.
I did not come across an iwinfo module for bmx6, just whatever additinional negative selector that may be required.

**Comment by aparcar** [comment]
>  I did not come across an iwinfo module for bmx6, just whatever additinional negative selector that may be required.

My bad, it's a BMX7 only feature :)

**Comment by aparcar** [comment]
> improve the description in the debian/control file.

@axn are you up for that?

**Comment by axn** [comment]
If not done already, I'll amend control file and add tags till Monday. But feel free to advance here as well. Any suggestions for a versioning scheme that facilitates frequent (interoprrable) updates? thanks for good progress

(Accidentally commented to #13 first)

**Pull request merged**
